# Task 1

# Q1
Write a function to compute 5/0 and use try/except to catch the exceptions

In [26]:
def trycatch():
    return 5/0

In [28]:
try:
    y= trycatch()
    print(y)
except:
    print("Denominator can not be 0")

Denominator can not be 1


# Q2.
Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [29]:
subject=["Americans", "Indians"]
verb=["Play", "watch"]
obj=["Baseball","Cricket"]

In [30]:
sentence_list = [(sub+" "+ vb + " " + ob) for sub in subject for vb in verb for ob in obj]

In [31]:
for sentence in sentence_list:
    print (sentence)

Americans Play Baseball
Americans Play Cricket
Americans watch Baseball
Americans watch Cricket
Indians Play Baseball
Indians Play Cricket
Indians watch Baseball
Indians watch Cricket


# Task 2

# Q1
Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1. HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [6]:
import numpy as np

In [16]:
def Vander_matrix(X, N, increasing=False):
    if increasing == False:
        return np.column_stack([x**(N-1-i) for i in range(N)])
    else:
        return np.column_stack([x**i for i in range(N)])
    

In [19]:
x = np.array([1, 2, 3, 5])
N = 3
Increasing = False
o = Vander_matrix(x,N, Increasing)


In [20]:
print(o)

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]


In [21]:
x = np.array([1, 2, 3, 5])
N = 3
Increasing = True
o = Vander_matrix(x,N, Increasing)

In [22]:
print(o)

[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  5 25]]
